import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

const translations = {
  en: {
    // Navbar
    homepage: 'Homepage',
    category: 'Category',
    allCategories: 'All Categories',
    searchProducts: 'Search products...',
    products: 'Products',
    about: 'About',
    contact: 'Contact',
    login: 'Log in',
    signup: 'Sign up',
    logout: 'Logout',
    admin: 'Admin',
    profile: 'Profile',
    categories: 'Categories',
    cart: 'Cart',
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    // Pages
    home: 'Home',
    shoppingCart: 'Shopping Cart',
    addToCart: 'Add to Cart',
    buyNow: 'Buy now',
    remove: 'Remove',
    quantity: 'Quantity',
    total: 'Total',
    checkout: 'Checkout',
    continueShopping: 'Continue Shopping',
    viewAll: 'View All',
    price: 'Price',
    description: 'Description',
    reviews: 'Reviews',
    relatedProducts: 'Related Products',
    noProductsFound: 'No products found',
    tryAdjustingFilters: 'Try adjusting your filters or search terms',
    filter: 'Filter',
    sortBy: 'Sort By',
    clearFilters: 'Clear Filters',
    available: 'available',
    page: 'Page',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    showing: 'Showing',
    to: 'to',
    outOfStock: 'Product is out of stock',
    addedToCart: 'Added to cart!',
    totalAmount: 'Total Amount',
    orderPlaced: 'Order Placed Successfully!',
    // Cart
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free',
    proceedToCheckout: 'Proceed to Checkout',
    // Contact
    sendMessage: 'Send Message',
    sending: 'Sending...',
    contactDescription: "We'd love to hear from you. Get in touch with us!",
    name: 'Name',
    email: 'Email',
    subject: 'Subject',
    message: 'Message',
    // Admin
    dashboard: 'Dashboard',
    orders: 'Orders',
    users: 'Users',
    messages: 'Messages',
    settings: 'Settings',
    // Home page
    newArrivals: 'New Arrivals Every Week',
    findPerfectProduct: 'Find Your Perfect',
    product: 'Product',
    discoverUnique: 'Discover unique products from around the world. Quality guaranteed, style unmatched.',
    shopNow: 'Shop Now',
    exploreCollection: 'Explore Collection',
    qualityGuaranteed: 'Quality Guaranteed',
    freeShipping: 'Free Shipping',
    securePayment: 'Secure Payment',
    scroll: 'Scroll',
    productsAvailable: 'products available',
    viewAllProducts: 'View All Products',
    // Products page
    allProducts: 'All Products',
    browseCollection: 'Browse our collection',
    productsFound: 'products found',
    productFound: 'product found',
    searchPlaceholder: 'Search products by name or description...',
    activeFilters: 'Active filters:',
    filters: 'Filters',
    clearAll: 'Clear all',
    clearAllFilters: 'Clear all filters',
    allSubcategories: 'All Subcategories',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    anyRating: 'Any Rating',
    allProductsFilter: 'All Products',
    inStock: 'In Stock',
    outOfStockFilter: 'Out of Stock',
    newestFirst: 'Newest First',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    highestRated: 'Highest Rated',
    loadingProducts: 'Loading products...',
    noProductsToDisplay: 'No products to display',
    showingProducts: 'Showing',
    acrossCategories: 'across categories',
    // Cart page
    cartEmpty: 'Your Cart is Empty',
    addProductsToCart: 'Add some products to your cart!',
    selectPaymentMethod: 'Select Payment Method',
    choosePaymentMethod: 'Choose Payment Method',
    cardPayment: 'Card Payment',
    cashOnDelivery: 'Cash on Delivery',
    cardDetails: 'Card Details',
    cardNumber: 'Card Number',
    cardholderName: 'Cardholder Name',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    codInfo: 'You will pay when you receive your order. Our delivery team will collect the payment at your doorstep.',
    deliveryInformation: 'Delivery Information',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    streetAddress: 'Street Address',
    city: 'City',
    stateProvince: 'State/Province',
    zipPostalCode: 'ZIP/Postal Code',
    country: 'Country',
    shippingAddress: 'Shipping Address',
    completeOrder: 'Complete Order',
    pay: 'Pay',
    placingOrder: 'Placing Order...',
    processingPayment: 'Processing Payment...',
    thankYouPurchase: 'Thank you for your purchase',
    orderId: 'Order ID',
    whatsNext: "What's Next?",
    orderReceived: "We've received your order and our team will contact you as soon as possible to confirm the details and arrange delivery. You'll receive an email confirmation shortly with your order information.",
    paymentMethod: 'Payment Method',
    orderStatus: 'Order Status',
    viewOrders: 'View Orders',
    // Product Detail
    inStockLabel: 'In Stock',
    outOfStockLabel: 'Out of Stock',
    stock: 'Stock',
    addToCartButton: 'Add to Cart',
    productDescription: 'Product Description',
    customerReviews: 'Customer Reviews',
    writeReview: 'Write a Review',
    rating: 'Rating',
    yourRating: 'Your Rating',
    yourComment: 'Your Comment',
    submitReview: 'Submit Review',
    pleaseLoginReview: 'Please login to submit a review',
    reviewSubmitted: 'Review submitted!',
    noReviews: 'No reviews yet',
    beFirstReview: 'Be the first to review this product!',
    youSave: 'You save',
    noImageAvailable: 'No Image Available',
    loadingProduct: 'Loading product details...',
    productOverview: 'Product Overview',
    productOverviewSubtitle: 'Detailed information about this product',
    productFeatures: 'Product Features',
    productFeaturesSubtitle: 'Key features and benefits of this product',
    whyChooseThisProduct: 'Why Choose This Product?',
    premiumFeatures: 'Premium features that set us apart',
    premiumQuality: 'Premium Quality',
    premiumQualityDesc: 'High-quality materials and craftsmanship ensure durability and long-lasting satisfaction.',
    fastDelivery: 'Fast Delivery',
    fastDeliveryDesc: 'Quick and reliable shipping to get your product to you as soon as possible.',
    securePurchase: 'Secure Purchase',
    securePurchaseDesc: 'Safe and secure payment options with comprehensive buyer protection guarantee.',
    seeWhatCustomersSaying: 'See what our customers are saying',
    shareYourExperience: 'Share your experience with this product...',
    readyToMakePurchase: 'Ready to Make a Purchase?',
    dontMissOut: 'Don\'t miss out on this exceptional product. Add it to your cart now or contact us directly for personalized assistance.',
    contactViaWhatsApp: 'Contact via WhatsApp',
    save: 'Save',
    youSaveAmount: 'You save',
    anonymousUser: 'Anonymous User',
    // About page
    aboutFindStore: 'About Find Store',
    trustedMarketplace: 'Your trusted marketplace for quality products from around the world',
    ourStory: 'Our Story',
    ourStoryText: 'Find Store was founded with a simple mission: to make quality products accessible to everyone, everywhere. We believe that shopping should be easy, enjoyable, and trustworthy.',
    ourStoryText2: "Since our launch, we've been committed to providing our customers with a curated selection of products, exceptional customer service, and a seamless shopping experience.",
    ourMission: 'Our Mission',
    ourMissionText: 'To connect customers with quality products while supporting sellers and creating a sustainable marketplace ecosystem. We\'re dedicated to:',
    exceptionalService: 'Providing exceptional customer service',
    productQuality: 'Ensuring product quality and authenticity',
    supportBusinesses: 'Supporting small businesses and independent sellers',
    safeEnvironment: 'Creating a safe and secure shopping environment',
    competitivePrices: 'Offering competitive prices and fast delivery',
    whyChooseUs: 'Why Choose Us',
    qualityGuaranteedTitle: 'Quality Guaranteed',
    qualityGuaranteedText: 'Every product is carefully vetted to ensure it meets our high quality standards.',
    fastDeliveryTitle: 'Fast Delivery',
    fastDeliveryText: 'We work with trusted shipping partners to get your orders to you quickly and safely.',
    secureShoppingTitle: 'Secure Shopping',
    secureShoppingText: 'Your payment information is protected with industry-standard encryption and security measures.',
    support247Title: '24/7 Support',
    support247Text: 'Our customer support team is available around the clock to help with any questions or concerns.',
    contactUs: 'Contact Us',
    contactUsText: "Have questions or feedback? We'd love to hear from you!",
    // Login/Register
    welcomeBack: 'Welcome back',
    signInContinue: 'Sign in to your account to continue',
    emailAddress: 'Email address',
    password: 'Password',
    signIn: 'Sign in',
    dontHaveAccount: "Don't have an account?",
    createOne: 'Create one',
    createAccount: 'Create your account',
    joinUs: 'Join us and start shopping today',
    fullNameLabel: 'Full Name',
    phoneOptional: 'Phone',
    phoneOptionalNote: '(Optional)',
    minimumCharacters: 'Must be at least 6 characters long',
    creatingAccount: 'Creating Account...',
    createAccountButton: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    signInLink: 'Sign in',
    signUpWithGoogle: 'Sign up with Google',
    signUpWithFacebook: 'Sign up with Facebook',
    or: 'or',
    // Profile
    myProfile: 'My Profile',
    manageAccount: 'Manage your account information and view order history',
    personalInformation: 'Personal Information',
    editProfile: 'Edit Profile',
    saveButton: 'Save',
    cancel: 'Cancel',
    orderHistory: 'Order History',
    totalOrders: 'total orders',
    noOrdersYet: 'No orders yet',
    orderHistoryAppear: 'Your order history will appear here',
    items: 'item',
    itemsPlural: 'items',
    loadingProfile: 'Loading profile...',
    // Contact page
    getInTouch: 'Get in Touch',
    contactHelp: "Have questions or need help? We're here to assist you. Reach out to us through any of the following channels.",
    phone: 'Phone',
    address: 'Address',
    phoneHours: 'Mon-Fri: 9am - 6pm EST',
    messageSentSuccess: 'Message sent successfully! We will get back to you soon.',
    // Review ratings
    ratingExcellent: '5 - Excellent',
    ratingVeryGood: '4 - Very Good',
    ratingGood: '3 - Good',
    ratingFair: '2 - Fair',
    ratingPoor: '1 - Poor',
    comment: 'Comment',
    // Payment
    paymentSystem: 'Payment System',
    comingSoon: 'Coming Soon!',
    paymentComingSoonText: "We're working hard to bring you a seamless payment experience. Checkout functionality will be available shortly.",
    // Footer
    helpCenter: 'Help Center',
    browseProducts: 'Browse Products',
    aboutUs: 'About Us',
    careers: 'Careers',
    privacyPolicy: 'Privacy Policy',
    terms: 'Terms',
    privacy: 'Privacy',
    sitemap: 'Sitemap',
    allRightsReserved: 'All rights reserved.',
    // Profile form
    uploadImageFromComputer: 'Upload Image from Computer',
    orEnterImageUrl: 'Or Enter Image URL',
    uploading: 'Uploading...',
    profileImageUploaded: 'Profile image uploaded successfully!',
    profileUpdated: 'Profile updated successfully!',
    street: 'Street',
    state: 'State',
    zipCode: 'Zip Code',
    // Placeholders
    placeholderEmail: 'you@example.com',
    placeholderName: 'John Doe',
    placeholderPhone: '+1 (555) 123-4567',
    placeholderPassword: 'Enter your password',
    placeholderYourName: 'Your name',
    placeholderYourEmail: 'your.email@example.com',
    placeholderSubject: "What's this about?",
    placeholderMessage: 'Your message here...',
    placeholderImageUrl: 'https://example.com/image.jpg',
    // Products page (filters)
    categoryFilter: 'Category:',
    searchFilter: 'Search:',
    priceFilter: 'Price:',
    ratingFilter: 'Rating:',
    any: 'Any',
    // Order details
    viewDetails: 'View Details',
    hideDetails: 'Hide Details',
    orderItems: 'Order Items',
    paymentInformation: 'Payment Information',
    contactInformation: 'Contact Information',
    paymentStatus: 'Payment Status',
    // Language names
    english: 'English',
    arabic: 'العربية',
    french: 'Français'
  },
  ar: {
    // Navbar
    homepage: 'الصفحة الرئيسية',
    category: 'الفئة',
    allCategories: 'جميع الفئات',
    searchProducts: 'البحث عن المنتجات...',
    products: 'المنتجات',
    about: 'من نحن',
    contact: 'اتصل بنا',
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    admin: 'المسؤول',
    profile: 'الملف الشخصي',
    categories: 'الفئات',
    cart: 'السلة',
    // Common
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجح',
    // Pages
    home: 'الرئيسية',
    shoppingCart: 'سلة التسوق',
    addToCart: 'أضف إلى السلة',
    buyNow: 'اشتري الآن',
    remove: 'إزالة',
    quantity: 'الكمية',
    total: 'المجموع',
    checkout: 'الدفع',
    continueShopping: 'متابعة التسوق',
    viewAll: 'عرض الكل',
    price: 'السعر',
    description: 'الوصف',
    reviews: 'التقييمات',
    relatedProducts: 'منتجات ذات صلة',
    noProductsFound: 'لم يتم العثور على منتجات',
    tryAdjustingFilters: 'حاول تعديل الفلاتر أو مصطلحات البحث',
    filter: 'تصفية',
    sortBy: 'ترتيب حسب',
    clearFilters: 'مسح الفلاتر',
    available: 'متاح',
    page: 'صفحة',
    of: 'من',
    previous: 'السابق',
    next: 'التالي',
    showing: 'عرض',
    to: 'إلى',
    outOfStock: 'المنتج غير متوفر',
    addedToCart: 'تمت الإضافة إلى السلة!',
    totalAmount: 'المبلغ الإجمالي',
    orderPlaced: 'تم تقديم الطلب بنجاح!',
    // Cart
    orderSummary: 'ملخص الطلب',
    subtotal: 'المجموع الفرعي',
    shipping: 'الشحن',
    free: 'مجاني',
    proceedToCheckout: 'المتابعة إلى الدفع',
    // Contact
    sendMessage: 'إرسال رسالة',
    sending: 'جاري الإرسال...',
    contactDescription: 'نود أن نسمع منك. تواصل معنا!',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    subject: 'الموضوع',
    message: 'الرسالة',
    // Admin
    dashboard: 'لوحة التحكم',
    orders: 'الطلبات',
    users: 'المستخدمون',
    messages: 'الرسائل',
    settings: 'الإعدادات',
    // Home page
    newArrivals: 'وصلات جديدة كل أسبوع',
    findPerfectProduct: 'ابحث عن منتجك المثالي',
    product: 'منتج',
    discoverUnique: 'اكتشف منتجات فريدة من جميع أنحاء العالم. الجودة مضمونة، والأناقة لا مثيل لها.',
    shopNow: 'تسوق الآن',
    exploreCollection: 'استكشف المجموعة',
    qualityGuaranteed: 'الجودة مضمونة',
    freeShipping: 'شحن مجاني',
    securePayment: 'دفع آمن',
    scroll: 'انتقل',
    productsAvailable: 'منتجات متاحة',
    viewAllProducts: 'عرض جميع المنتجات',
    // Products page
    allProducts: 'جميع المنتجات',
    browseCollection: 'تصفح مجموعتنا',
    productsFound: 'منتج موجود',
    productFound: 'منتج موجود',
    searchPlaceholder: 'البحث عن المنتجات بالاسم أو الوصف...',
    activeFilters: 'الفلاتر النشطة:',
    filters: 'الفلاتر',
    clearAll: 'مسح الكل',
    clearAllFilters: 'مسح جميع الفلاتر',
    allSubcategories: 'جميع الفئات الفرعية',
    minPrice: 'أقل سعر',
    maxPrice: 'أعلى سعر',
    anyRating: 'أي تقييم',
    allProductsFilter: 'جميع المنتجات',
    inStock: 'متوفر',
    outOfStockFilter: 'غير متوفر',
    newestFirst: 'الأحدث أولاً',
    priceLowToHigh: 'السعر: من الأقل إلى الأعلى',
    priceHighToLow: 'السعر: من الأعلى إلى الأقل',
    highestRated: 'الأعلى تقييماً',
    loadingProducts: 'جاري تحميل المنتجات...',
    noProductsToDisplay: 'لا توجد منتجات للعرض',
    showingProducts: 'عرض',
    acrossCategories: 'عبر الفئات',
    // Cart page
    cartEmpty: 'سلة التسوق فارغة',
    addProductsToCart: 'أضف بعض المنتجات إلى سلة التسوق!',
    selectPaymentMethod: 'اختر طريقة الدفع',
    choosePaymentMethod: 'اختر طريقة الدفع',
    cardPayment: 'الدفع بالبطاقة',
    cashOnDelivery: 'الدفع عند الاستلام',
    cardDetails: 'تفاصيل البطاقة',
    cardNumber: 'رقم البطاقة',
    cardholderName: 'اسم حامل البطاقة',
    expiryDate: 'تاريخ الانتهاء',
    cvv: 'CVV',
    codInfo: 'ستدفع عند استلام طلبك. سيقوم فريق التوصيل لدينا بتحصيل الدفع عند باب منزلك.',
    deliveryInformation: 'معلومات التوصيل',
    fullName: 'الاسم الكامل',
    phoneNumber: 'رقم الهاتف',
    streetAddress: 'عنوان الشارع',
    city: 'المدينة',
    stateProvince: 'الولاية/المحافظة',
    zipPostalCode: 'الرمز البريدي',
    country: 'الدولة',
    shippingAddress: 'عنوان الشحن',
    completeOrder: 'إتمام الطلب',
    pay: 'دفع',
    placingOrder: 'جاري تقديم الطلب...',
    processingPayment: 'جاري معالجة الدفع...',
    thankYouPurchase: 'شكراً لك على الشراء',
    orderId: 'رقم الطلب',
    whatsNext: 'ماذا بعد؟',
    orderReceived: 'لقد استلمنا طلبك وسيتصل بك فريقنا في أقرب وقت ممكن لتأكيد التفاصيل وترتيب التوصيل. ستصلك رسالة تأكيد بالبريد الإلكتروني قريباً مع معلومات طلبك.',
    paymentMethod: 'طريقة الدفع',
    orderStatus: 'حالة الطلب',
    viewOrders: 'عرض الطلبات',
    // Product Detail
    inStockLabel: 'متوفر',
    outOfStockLabel: 'غير متوفر',
    stock: 'المخزون',
    addToCartButton: 'أضف إلى السلة',
    productDescription: 'وصف المنتج',
    customerReviews: 'تقييمات العملاء',
    writeReview: 'اكتب تقييماً',
    rating: 'التقييم',
    yourRating: 'تقييمك',
    yourComment: 'تعليقك',
    submitReview: 'إرسال التقييم',
    pleaseLoginReview: 'يرجى تسجيل الدخول لإرسال تقييم',
    reviewSubmitted: 'تم إرسال التقييم!',
    noReviews: 'لا توجد تقييمات بعد',
    beFirstReview: 'كن أول من يقيم هذا المنتج!',
    youSave: 'توفر',
    noImageAvailable: 'لا توجد صورة متاحة',
    loadingProduct: 'جاري تحميل تفاصيل المنتج...',
    productOverview: 'نظرة عامة على المنتج',
    productOverviewSubtitle: 'معلومات تفصيلية عن هذا المنتج',
    productFeatures: 'مميزات المنتج',
    productFeaturesSubtitle: 'المميزات والفوائد الرئيسية لهذا المنتج',
    whyChooseThisProduct: 'لماذا تختار هذا المنتج؟',
    premiumFeatures: 'ميزات مميزة تميزنا عن الآخرين',
    premiumQuality: 'جودة عالية',
    premiumQualityDesc: 'مواد عالية الجودة وحرفية متميزة تضمن المتانة والرضا طويل الأمد.',
    fastDelivery: 'توصيل سريع',
    fastDeliveryDesc: 'شحن سريع وموثوق لتوصيل منتجك إليك في أقرب وقت ممكن.',
    securePurchase: 'شراء آمن',
    securePurchaseDesc: 'خيارات دفع آمنة ومأمونة مع ضمان حماية المشتري الشامل.',
    seeWhatCustomersSaying: 'شاهد ما يقوله عملاؤنا',
    shareYourExperience: 'شارك تجربتك مع هذا المنتج...',
    readyToMakePurchase: 'هل أنت مستعد لإجراء عملية شراء؟',
    dontMissOut: 'لا تفوت هذا المنتج الاستثنائي. أضفه إلى سلة التسوق الآن أو اتصل بنا مباشرة للحصول على مساعدة مخصصة.',
    contactViaWhatsApp: 'التواصل عبر واتساب',
    save: 'وفر',
    youSaveAmount: 'توفر',
    anonymousUser: 'مستخدم مجهول',
    // About page
    aboutFindStore: 'حول Find Store',
    trustedMarketplace: 'سوقك الموثوق للمنتجات عالية الجودة من جميع أنحاء العالم',
    ourStory: 'قصتنا',
    ourStoryText: 'تأسست Find Store بمهمة بسيطة: جعل المنتجات عالية الجودة في متناول الجميع، في كل مكان. نؤمن بأن التسوق يجب أن يكون سهلاً وممتعاً وموثوقاً.',
    ourStoryText2: 'منذ إطلاقنا، كنا ملتزمين بتزويد عملائنا باختيار منتقى من المنتجات، وخدمة عملاء استثنائية، وتجربة تسوق سلسة.',
    ourMission: 'مهمتنا',
    ourMissionText: 'ربط العملاء بمنتجات عالية الجودة مع دعم البائعين وإنشاء نظام بيئي سوقي مستدام. نحن ملتزمون بـ:',
    exceptionalService: 'توفير خدمة عملاء استثنائية',
    productQuality: 'ضمان جودة المنتج وأصالته',
    supportBusinesses: 'دعم الشركات الصغيرة والبائعين المستقلين',
    safeEnvironment: 'إنشاء بيئة تسوق آمنة ومأمونة',
    competitivePrices: 'تقديم أسعار تنافسية وتوصيل سريع',
    whyChooseUs: 'لماذا تختارنا',
    qualityGuaranteedTitle: 'الجودة مضمونة',
    qualityGuaranteedText: 'يتم فحص كل منتج بعناية لضمان استيفائه لمعايير الجودة العالية لدينا.',
    fastDeliveryTitle: 'توصيل سريع',
    fastDeliveryText: 'نعمل مع شركاء شحن موثوقين لتوصيل طلباتك إليك بسرعة وأمان.',
    secureShoppingTitle: 'تسوق آمن',
    secureShoppingText: 'معلومات الدفع الخاصة بك محمية بتشفير وإجراءات أمنية معيارية في الصناعة.',
    support247Title: 'دعم على مدار الساعة',
    support247Text: 'فريق دعم العملاء لدينا متاح على مدار الساعة لمساعدتك في أي أسئلة أو مخاوف.',
    contactUs: 'اتصل بنا',
    contactUsText: 'هل لديك أسئلة أو ملاحظات؟ نحب أن نسمع منك!',
    // Login/Register
    welcomeBack: 'مرحباً بعودتك',
    signInContinue: 'قم بتسجيل الدخول إلى حسابك للمتابعة',
    emailAddress: 'عنوان البريد الإلكتروني',
    password: 'كلمة المرور',
    signIn: 'تسجيل الدخول',
    dontHaveAccount: 'ليس لديك حساب؟',
    createOne: 'إنشاء حساب',
    createAccount: 'إنشاء حسابك',
    joinUs: 'انضم إلينا وابدأ التسوق اليوم',
    fullNameLabel: 'الاسم الكامل',
    phoneOptional: 'الهاتف',
    phoneOptionalNote: '(اختياري)',
    minimumCharacters: 'يجب أن يكون 6 أحرف على الأقل',
    creatingAccount: 'جاري إنشاء الحساب...',
    createAccountButton: 'إنشاء حساب',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    signInLink: 'تسجيل الدخول',
    signUpWithGoogle: 'التسجيل عبر Google',
    signUpWithFacebook: 'التسجيل عبر Facebook',
    or: 'أو',
    // Profile
    myProfile: 'ملفي الشخصي',
    manageAccount: 'إدارة معلومات حسابك وعرض سجل الطلبات',
    personalInformation: 'المعلومات الشخصية',
    editProfile: 'تعديل الملف الشخصي',
    saveButton: 'حفظ',
    cancel: 'إلغاء',
    orderHistory: 'سجل الطلبات',
    totalOrders: 'إجمالي الطلبات',
    noOrdersYet: 'لا توجد طلبات بعد',
    orderHistoryAppear: 'سيظهر سجل طلباتك هنا',
    items: 'عنصر',
    itemsPlural: 'عناصر',
    loadingProfile: 'جاري تحميل الملف الشخصي...',
    // Contact page
    getInTouch: 'تواصل معنا',
    contactHelp: 'هل لديك أسئلة أو تحتاج إلى مساعدة؟ نحن هنا لمساعدتك. تواصل معنا من خلال أي من القنوات التالية.',
    phone: 'الهاتف',
    address: 'العنوان',
    phoneHours: 'الإثنين-الجمعة: 9 صباحاً - 6 مساءً',
    messageSentSuccess: 'تم إرسال الرسالة بنجاح! سنعود إليك قريباً.',
    // Review ratings
    ratingExcellent: '5 - ممتاز',
    ratingVeryGood: '4 - جيد جداً',
    ratingGood: '3 - جيد',
    ratingFair: '2 - مقبول',
    ratingPoor: '1 - ضعيف',
    comment: 'تعليق',
    // Payment
    paymentSystem: 'نظام الدفع',
    comingSoon: 'قريباً!',
    paymentComingSoonText: 'نعمل بجد لتقديم تجربة دفع سلسة لك. ستكون وظيفة الدفع متاحة قريباً.',
    // Footer
    helpCenter: 'مركز المساعدة',
    browseProducts: 'تصفح المنتجات',
    aboutUs: 'من نحن',
    careers: 'الوظائف',
    privacyPolicy: 'سياسة الخصوصية',
    terms: 'الشروط',
    privacy: 'الخصوصية',
    sitemap: 'خريطة الموقع',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    // Profile form
    uploadImageFromComputer: 'رفع صورة من الكمبيوتر',
    orEnterImageUrl: 'أو أدخل رابط الصورة',
    uploading: 'جاري الرفع...',
    profileImageUploaded: 'تم رفع صورة الملف الشخصي بنجاح!',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
    street: 'الشارع',
    state: 'الحالة',
    zipCode: 'الرمز البريدي',
    // Placeholders
    placeholderEmail: 'you@example.com',
    placeholderName: 'جون دو',
    placeholderPhone: '+212 707625535',
    placeholderPassword: 'أدخل كلمة المرور',
    placeholderYourName: 'اسمك',
    placeholderYourEmail: 'your.email@example.com',
    placeholderSubject: 'ما هذا الموضوع؟',
    placeholderMessage: 'رسالتك هنا...',
    placeholderImageUrl: 'https://example.com/image.jpg',
    // Products page (filters)
    categoryFilter: 'الفئة:',
    searchFilter: 'البحث:',
    priceFilter: 'السعر:',
    ratingFilter: 'التقييم:',
    any: 'أي',
    // Order details
    viewDetails: 'عرض التفاصيل',
    hideDetails: 'إخفاء التفاصيل',
    orderItems: 'عناصر الطلب',
    paymentInformation: 'معلومات الدفع',
    contactInformation: 'معلومات الاتصال',
    paymentStatus: 'حالة الدفع',
    // Language names
    english: 'English',
    arabic: 'العربية',
    french: 'Français'
  },
  fr: {
    // Navbar
    homepage: 'Accueil',
    category: 'Catégorie',
    allCategories: 'Toutes les catégories',
    searchProducts: 'Rechercher des produits...',
    products: 'Produits',
    about: 'À propos',
    contact: 'Contact',
    login: 'Se connecter',
    signup: "S'inscrire",
    logout: 'Déconnexion',
    admin: 'Administrateur',
    profile: 'Profil',
    categories: 'Catégories',
    cart: 'Panier',
    // Common
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    // Pages
    home: 'Accueil',
    shoppingCart: 'Panier',
    addToCart: 'Ajouter au panier',
    buyNow: 'Acheter maintenant',
    remove: 'Retirer',
    quantity: 'Quantité',
    total: 'Total',
    checkout: 'Commander',
    continueShopping: 'Continuer les achats',
    viewAll: 'Voir tout',
    price: 'Prix',
    description: 'Description',
    reviews: 'Avis',
    relatedProducts: 'Produits connexes',
    noProductsFound: 'Aucun produit trouvé',
    tryAdjustingFilters: 'Essayez d\'ajuster vos filtres ou termes de recherche',
    filter: 'Filtrer',
    sortBy: 'Trier par',
    clearFilters: 'Effacer les filtres',
    available: 'disponible',
    page: 'Page',
    of: 'de',
    previous: 'Précédent',
    next: 'Suivant',
    showing: 'Affichage',
    to: 'à',
    outOfStock: 'Produit en rupture de stock',
    addedToCart: 'Ajouté au panier!',
    totalAmount: 'Montant total',
    orderPlaced: 'Commande passée avec succès!',
    // Cart
    orderSummary: 'Résumé de la commande',
    subtotal: 'Sous-total',
    shipping: 'Livraison',
    free: 'Gratuit',
    proceedToCheckout: 'Passer à la caisse',
    // Contact
    sendMessage: 'Envoyer un message',
    sending: 'Envoi en cours...',
    contactDescription: "Nous aimerions avoir de vos nouvelles. Contactez-nous!",
    name: 'Nom',
    email: 'Email',
    subject: 'Sujet',
    message: 'Message',
    // Admin
    dashboard: 'Tableau de bord',
    orders: 'Commandes',
    users: 'Utilisateurs',
    messages: 'Messages',
    settings: 'Paramètres',
    // Home page
    newArrivals: 'Nouveautés chaque semaine',
    findPerfectProduct: 'Trouvez votre produit parfait',
    product: 'Produit',
    discoverUnique: 'Découvrez des produits uniques du monde entier. Qualité garantie, style inégalé.',
    shopNow: 'Acheter maintenant',
    exploreCollection: 'Explorer la collection',
    qualityGuaranteed: 'Qualité garantie',
    freeShipping: 'Livraison gratuite',
    securePayment: 'Paiement sécurisé',
    scroll: 'Défiler',
    productsAvailable: 'produits disponibles',
    viewAllProducts: 'Voir tous les produits',
    // Products page
    allProducts: 'Tous les produits',
    browseCollection: 'Parcourez notre collection',
    productsFound: 'produits trouvés',
    productFound: 'produit trouvé',
    searchPlaceholder: 'Rechercher des produits par nom ou description...',
    activeFilters: 'Filtres actifs:',
    filters: 'Filtres',
    clearAll: 'Tout effacer',
    clearAllFilters: 'Effacer tous les filtres',
    allSubcategories: 'Toutes les sous-catégories',
    minPrice: 'Prix minimum',
    maxPrice: 'Prix maximum',
    anyRating: 'N\'importe quelle note',
    allProductsFilter: 'Tous les produits',
    inStock: 'En stock',
    outOfStockFilter: 'Rupture de stock',
    newestFirst: 'Plus récent d\'abord',
    priceLowToHigh: 'Prix: Du plus bas au plus haut',
    priceHighToLow: 'Prix: Du plus haut au plus bas',
    highestRated: 'Mieux notés',
    loadingProducts: 'Chargement des produits...',
    noProductsToDisplay: 'Aucun produit à afficher',
    showingProducts: 'Affichage',
    acrossCategories: 'à travers les catégories',
    // Cart page
    cartEmpty: 'Votre panier est vide',
    addProductsToCart: 'Ajoutez des produits à votre panier!',
    selectPaymentMethod: 'Sélectionner le mode de paiement',
    choosePaymentMethod: 'Choisir le mode de paiement',
    cardPayment: 'Paiement par carte',
    cashOnDelivery: 'Paiement à la livraison',
    cardDetails: 'Détails de la carte',
    cardNumber: 'Numéro de carte',
    cardholderName: 'Nom du titulaire',
    expiryDate: 'Date d\'expiration',
    cvv: 'CVV',
    codInfo: 'Vous paierez lors de la réception de votre commande. Notre équipe de livraison collectera le paiement à votre porte.',
    deliveryInformation: 'Informations de livraison',
    fullName: 'Nom complet',
    phoneNumber: 'Numéro de téléphone',
    streetAddress: 'Adresse',
    city: 'Ville',
    stateProvince: 'État/Province',
    zipPostalCode: 'Code postal',
    country: 'Pays',
    shippingAddress: 'Adresse de livraison',
    completeOrder: 'Finaliser la commande',
    pay: 'Payer',
    placingOrder: 'Passage de commande...',
    processingPayment: 'Traitement du paiement...',
    thankYouPurchase: 'Merci pour votre achat',
    orderId: 'Numéro de commande',
    whatsNext: 'Et maintenant?',
    orderReceived: 'Nous avons reçu votre commande et notre équipe vous contactera dès que possible pour confirmer les détails et organiser la livraison. Vous recevrez un e-mail de confirmation sous peu avec les informations de votre commande.',
    paymentMethod: 'Mode de paiement',
    orderStatus: 'Statut de la commande',
    viewOrders: 'Voir les commandes',
    // Product Detail
    inStockLabel: 'En stock',
    outOfStockLabel: 'Rupture de stock',
    stock: 'Stock',
    addToCartButton: 'Ajouter au panier',
    productDescription: 'Description du produit',
    customerReviews: 'Avis clients',
    writeReview: 'Écrire un avis',
    rating: 'Note',
    yourRating: 'Votre note',
    yourComment: 'Votre commentaire',
    submitReview: 'Soumettre l\'avis',
    pleaseLoginReview: 'Veuillez vous connecter pour soumettre un avis',
    reviewSubmitted: 'Avis soumis!',
    noReviews: 'Aucun avis pour le moment',
    beFirstReview: 'Soyez le premier à noter ce produit!',
    youSave: 'Vous économisez',
    noImageAvailable: 'Aucune image disponible',
    loadingProduct: 'Chargement des détails du produit...',
    productOverview: 'Aperçu du produit',
    productOverviewSubtitle: 'Informations détaillées sur ce produit',
    productFeatures: 'Caractéristiques du produit',
    productFeaturesSubtitle: 'Caractéristiques et avantages clés de ce produit',
    whyChooseThisProduct: 'Pourquoi choisir ce produit?',
    premiumFeatures: 'Fonctionnalités premium qui nous distinguent',
    premiumQuality: 'Qualité premium',
    premiumQualityDesc: 'Des matériaux de haute qualité et un savoir-faire artisanal garantissent durabilité et satisfaction durable.',
    fastDelivery: 'Livraison rapide',
    fastDeliveryDesc: 'Expédition rapide et fiable pour vous livrer votre produit au plus vite.',
    securePurchase: 'Achat sécurisé',
    securePurchaseDesc: 'Options de paiement sûres et sécurisées avec garantie complète de protection de l\'acheteur.',
    seeWhatCustomersSaying: 'Découvrez ce que disent nos clients',
    shareYourExperience: 'Partagez votre expérience avec ce produit...',
    readyToMakePurchase: 'Prêt à faire un achat?',
    dontMissOut: 'Ne manquez pas ce produit exceptionnel. Ajoutez-le à votre panier maintenant ou contactez-nous directement pour une assistance personnalisée.',
    contactViaWhatsApp: 'Contacter via WhatsApp',
    save: 'Économiser',
    youSaveAmount: 'Vous économisez',
    anonymousUser: 'Utilisateur anonyme',
    // About page
    aboutFindStore: 'À propos de Find Store',
    trustedMarketplace: 'Votre marché de confiance pour des produits de qualité du monde entier',
    ourStory: 'Notre histoire',
    ourStoryText: 'Find Store a été fondé avec une mission simple: rendre les produits de qualité accessibles à tous, partout. Nous croyons que le shopping devrait être facile, agréable et fiable.',
    ourStoryText2: 'Depuis notre lancement, nous nous sommes engagés à fournir à nos clients une sélection de produits soignée, un service client exceptionnel et une expérience d\'achat fluide.',
    ourMission: 'Notre mission',
    ourMissionText: 'Connecter les clients avec des produits de qualité tout en soutenant les vendeurs et en créant un écosystème de marché durable. Nous nous engageons à:',
    exceptionalService: 'Fournir un service client exceptionnel',
    productQuality: 'Garantir la qualité et l\'authenticité des produits',
    supportBusinesses: 'Soutenir les petites entreprises et les vendeurs indépendants',
    safeEnvironment: 'Créer un environnement d\'achat sûr et sécurisé',
    competitivePrices: 'Offrir des prix compétitifs et une livraison rapide',
    whyChooseUs: 'Pourquoi nous choisir',
    qualityGuaranteedTitle: 'Qualité garantie',
    qualityGuaranteedText: 'Chaque produit est soigneusement vérifié pour garantir qu\'il répond à nos normes de qualité élevées.',
    fastDeliveryTitle: 'Livraison rapide',
    fastDeliveryText: 'Nous travaillons avec des partenaires d\'expédition de confiance pour vous livrer vos commandes rapidement et en toute sécurité.',
    secureShoppingTitle: 'Achat sécurisé',
    secureShoppingText: 'Vos informations de paiement sont protégées par un cryptage et des mesures de sécurité standard de l\'industrie.',
    support247Title: 'Support 24/7',
    support247Text: 'Notre équipe de support client est disponible 24h/24 et 7j/7 pour vous aider avec toutes vos questions ou préoccupations.',
    contactUs: 'Contactez-nous',
    contactUsText: 'Vous avez des questions ou des commentaires? Nous aimerions avoir de vos nouvelles!',
    // Login/Register
    welcomeBack: 'Bon retour',
    signInContinue: 'Connectez-vous à votre compte pour continuer',
    emailAddress: 'Adresse e-mail',
    password: 'Mot de passe',
    signIn: 'Se connecter',
    dontHaveAccount: 'Vous n\'avez pas de compte?',
    createOne: 'Créer un compte',
    createAccount: 'Créez votre compte',
    joinUs: 'Rejoignez-nous et commencez à magasiner aujourd\'hui',
    fullNameLabel: 'Nom complet',
    phoneOptional: 'Téléphone',
    phoneOptionalNote: '(Optionnel)',
    minimumCharacters: 'Doit contenir au moins 6 caractères',
    creatingAccount: 'Création du compte...',
    createAccountButton: 'Créer un compte',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    signInLink: 'Se connecter',
    signUpWithGoogle: 'S\'inscrire avec Google',
    signUpWithFacebook: 'S\'inscrire avec Facebook',
    or: 'ou',
    // Profile
    myProfile: 'Mon profil',
    manageAccount: 'Gérez les informations de votre compte et consultez l\'historique des commandes',
    personalInformation: 'Informations personnelles',
    editProfile: 'Modifier le profil',
    saveButton: 'Enregistrer',
    cancel: 'Annuler',
    orderHistory: 'Historique des commandes',
    totalOrders: 'commandes au total',
    noOrdersYet: 'Aucune commande pour le moment',
    orderHistoryAppear: 'Votre historique de commandes apparaîtra ici',
    items: 'article',
    itemsPlural: 'articles',
    loadingProfile: 'Chargement du profil...',
    // Contact page
    getInTouch: 'Contactez-nous',
    contactHelp: 'Vous avez des questions ou besoin d\'aide? Nous sommes là pour vous aider. Contactez-nous via l\'un des canaux suivants.',
    phone: 'Téléphone',
    address: 'Adresse',
    phoneHours: 'Lun-Ven: 9h - 18h',
    messageSentSuccess: 'Message envoyé avec succès! Nous vous répondrons bientôt.',
    // Review ratings
    ratingExcellent: '5 - Excellent',
    ratingVeryGood: '4 - Très bien',
    ratingGood: '3 - Bien',
    ratingFair: '2 - Passable',
    ratingPoor: '1 - Mauvais',
    comment: 'Commentaire',
    // Payment
    paymentSystem: 'Système de paiement',
    comingSoon: 'Bientôt disponible!',
    paymentComingSoonText: 'Nous travaillons dur pour vous offrir une expérience de paiement fluide. La fonctionnalité de paiement sera disponible sous peu.',
    // Footer
    helpCenter: 'Centre d\'aide',
    browseProducts: 'Parcourir les produits',
    aboutUs: 'À propos',
    careers: 'Carrières',
    privacyPolicy: 'Politique de confidentialité',
    terms: 'Conditions',
    privacy: 'Confidentialité',
    sitemap: 'Plan du site',
    allRightsReserved: 'Tous droits réservés.',
    // Profile form
    uploadImageFromComputer: 'Télécharger une image depuis l\'ordinateur',
    orEnterImageUrl: 'Ou entrer l\'URL de l\'image',
    uploading: 'Téléchargement...',
    profileImageUploaded: 'Image de profil téléchargée avec succès!',
    profileUpdated: 'Profil mis à jour avec succès!',
    street: 'Rue',
    state: 'État',
    zipCode: 'Code postal',
    // Placeholders
    placeholderEmail: 'you@example.com',
    placeholderName: 'Jean Dupont',
    placeholderPhone: '+33 1 23 45 67 89',
    placeholderPassword: 'Entrez votre mot de passe',
    placeholderYourName: 'Votre nom',
    placeholderYourEmail: 'your.email@example.com',
    placeholderSubject: 'De quoi s\'agit-il?',
    placeholderMessage: 'Votre message ici...',
    placeholderImageUrl: 'https://example.com/image.jpg',
    // Products page (filters)
    categoryFilter: 'Catégorie:',
    searchFilter: 'Recherche:',
    priceFilter: 'Prix:',
    ratingFilter: 'Note:',
    any: 'Tout',
    // Order details
    viewDetails: 'Voir les détails',
    hideDetails: 'Masquer les détails',
    orderItems: 'Articles de commande',
    paymentInformation: 'Informations de paiement',
    contactInformation: 'Informations de contact',
    paymentStatus: 'Statut du paiement',
    // Language names
    english: 'English',
    arabic: 'العربية',
    french: 'Français'
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language')
    return saved || 'en'
  })

  useEffect(() => {
    localStorage.setItem('language', language)
    // Update document direction for RTL languages
    if (language === 'ar') {
      document.documentElement.setAttribute('dir', 'rtl')
      document.documentElement.setAttribute('lang', 'ar')
      document.body.setAttribute('dir', 'rtl')
    } else {
      document.documentElement.setAttribute('dir', 'ltr')
      document.documentElement.setAttribute('lang', language)
      document.body.setAttribute('dir', 'ltr')
    }
  }, [language])

  const t = (key) => {
    return translations[language]?.[key] || key
  }

  const changeLanguage = (lang) => {
    setLanguage(lang)
  }

  const value = {
    language,
    changeLanguage,
    t,
    // RTL only for Arabic, LTR for French and English
    isRTL: language === 'ar'
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
